# Generated by Django 5.1.5 on 2025-03-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_id", models.IntegerField(null=True)),
                ("name", models.CharField(max_length=200)),
                ("dept_name", models.CharField(max_length=500)),
                ("dept_description", models.CharField(max_length=500)),
                ("dept_head", models.CharField(max_length=200)),
                (
                    "dept_head_email",
                    models.EmailField(default="admin@gmail.com", max_length=200),
                ),
                ("dept_head_phone", models.CharField(max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(default=None, verbose_name="date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=None, verbose_name="date updated"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssueCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_id", models.IntegerField(null=True)),
                ("category_name", models.CharField(max_length=200)),
                ("category_description", models.CharField(max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(default=None, verbose_name="date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=None, verbose_name="date updated"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssueStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_id", models.IntegerField(null=True)),
                ("status_name", models.CharField(default=None, max_length=200)),
                ("status_description", models.CharField(default=None, max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(default=None, verbose_name="date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=None, verbose_name="date updated"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Priority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority_id", models.IntegerField(null=True)),
                ("priority_name", models.CharField(default=None, max_length=200)),
                (
                    "priority_description",
                    models.CharField(default=None, max_length=200),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=None, verbose_name="date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=None, verbose_name="date updated"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=200)),
                ("role_description", models.CharField(max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(default=None, verbose_name="date created"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.IntegerField(null=True)),
                ("group_name", models.CharField(default=None, max_length=200)),
                ("group_description", models.CharField(default=None, max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(default=None, verbose_name="date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=None, verbose_name="date updated"),
                ),
                (
                    "department_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aits.departments",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_id", models.IntegerField(null=True)),
                ("description", models.CharField(max_length=200, null=True)),
                ("title", models.CharField(max_length=300, null=True)),
                (
                    "pub_date",
                    models.DateTimeField(default=None, verbose_name="date published"),
                ),
                (
                    "creation_date",
                    models.DateTimeField(default=None, verbose_name="date created"),
                ),
                (
                    "updated_date",
                    models.DateTimeField(default=None, verbose_name="date updated"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(default=None, verbose_name="date resolved"),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aits.issuecategory",
                    ),
                ),
                (
                    "user_group_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aits.group",
                    ),
                ),
                (
                    "status_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aits.issuestatus",
                    ),
                ),
                (
                    "priority_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aits.priority",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(null=True)),
                ("fullname", models.CharField(default=None, max_length=200)),
                ("username", models.CharField(default=None, max_length=200)),
                ("email", models.EmailField(default="aits@gmail.com", max_length=200)),
                ("student_number", models.IntegerField(default=None)),
                ("password", models.CharField(default=None, max_length=200)),
                (
                    "last_login",
                    models.DateTimeField(default=None, verbose_name="date last login"),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "department_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aits.departments",
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aits.role"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notifications_id", models.CharField(default=None, max_length=200)),
                ("message", models.CharField(default=None, max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(default=None, verbose_name="date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=None, verbose_name="date updated"),
                ),
                ("type", models.CharField(max_length=200)),
                ("read", models.BooleanField(default=False)),
                (
                    "group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aits.group"
                    ),
                ),
                (
                    "issue_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aits.issues"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aits.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="issues",
            name="user_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="aits.user",
            ),
        ),
        migrations.CreateModel(
            name="IssueHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=None, verbose_name="date_created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=None, verbose_name="date updated"),
                ),
                (
                    "issue_history_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aits.issues"
                    ),
                ),
                (
                    "status_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aits.issuestatus",
                    ),
                ),
                (
                    "assigned_toId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aits.user",
                    ),
                ),
            ],
        ),
    ]
