# Generated by Django 5.1.5 on 2025-03-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aits", "0002_remove_group_department_id_remove_user_department_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="student_number",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("lecturer", "Lecturer"),
                    ("head_of_department", "Head of Department"),
                    ("academic_registrar", "Academic Registrar"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
