# Generated by Django 5.1.7 on 2025-04-01 10:04

from django.db import migrations

def copy_student_number_to_registration_number(apps, schema_editor):
    """
    Copy student_number values to registration_number and set department from program
    """
    Student = apps.get_model('users', 'Student')
    
    for student in Student.objects.all():
        # Copy student_number to registration_number if registration_number is not set
        if not student.registration_number:
            student.registration_number = student.student_number
        
        # Set department from program's department if program exists
        if student.program_id and not student.department_id:
            program = student.program
            if hasattr(program, 'department'):
                student.department = program.department
        
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_department_student_registration_number_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_student_number_to_registration_number),
    ]
