# Generated by Django 5.1.7 on 2025-04-01 10:12

from django.db import migrations, models
import django.db.models.deletion

def ensure_no_nulls(apps, schema_editor):
    """
    Ensure no null values remain in the required fields
    """
    Student = apps.get_model('users', 'Student')
    Department = apps.get_model('academic', 'Department')
    
    # Get a default department if needed
    default_department = None
    if Department.objects.exists():
        default_department = Department.objects.first()
    
    for student in Student.objects.all():
        # Handle null student_number
        if not student.student_number:
            student.student_number = f"STU-{student.student_id}"
        
        # Handle null registration_number
        if not student.registration_number:
            student.registration_number = f"REG-{student.student_id}"
        
        # Handle null department
        if not student.department_id:
            if default_department:
                student.department = default_department
            # If no department exists and no default can be created,
            # we need to create a temporary department
            elif student.program and hasattr(student.program, 'department'):
                student.department = student.program.department
        
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250401_1310'),
    ]

    operations = [
        migrations.RunPython(ensure_no_nulls),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_students', to='academic.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(help_text='Registration/enrollment number', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(help_text='Unique student identifier number', max_length=20, unique=True),
        ),
    ]
