# Generated by Django 5.1.7 on 2025-04-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20250401_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(default=1, help_text='Cumulative semester number throughout the program (1-8 for 4 years, 1-10 for 5 years)'),
        ),
        migrations.AddField(
            model_name='student',
            name='semester_in_year',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1, help_text='Current semester within the academic year (1 or 2)'),
        ),
    ]
