# Generated by Django 5.1.7 on 2025-04-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20250401_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.IntegerField(help_text='Unique student identifier number', unique=True),
        ),
    ]
