# Generated by Django 5.1.7 on 2025-03-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_add_open_status'),
        ('issues', '0003_alter_attachment_issue'),
    ]

    operations = [
    ]
