# Generated by Django 5.1.7 on 2025-04-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_add_critical_priority'),
        ('issues', '0004_merge_20250327_1444'),
    ]

    operations = [
    ]
