import React from 'react';
import { Link } from 'react-router-dom';
import {
  ChatBubbleLeftRightIcon,
  BellIcon,
  ChatBubbleLeftIcon,
  ArrowLeftIcon
} from '@heroicons/react/24/outline';

const CommunicationGuide = () => {
  return (
    <div className="p-8 max-w-4xl mx-auto">
      <div className="mb-8">
        <Link
          to="/docs"
          className="text-blue-600 hover:text-blue-800 flex items-center"
        >
          <ArrowLeftIcon className="h-5 w-5 mr-2" /> Back to Documentation
        </Link>
      </div>

      <div className="bg-white rounded-lg shadow overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-200">
          <h1 className="text-2xl font-semibold text-gray-900">Communication Guide</h1>
        </div>

        <div className="px-6 py-4">
          <div className="prose max-w-none">
            <h2 className="text-xl font-semibold mb-4">Understanding Communication Channels</h2>
            <p className="mb-6">
              The MUK Support Portal offers three different communication channels, each designed for specific purposes.
              Understanding when to use each channel will help you communicate effectively and efficiently.
            </p>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
              <div className="bg-blue-50 p-6 rounded-lg border border-blue-200">
                <div className="flex items-center mb-4">
                  <ChatBubbleLeftRightIcon className="h-8 w-8 text-blue-500 mr-3" />
                  <h3 className="text-lg font-medium text-blue-900">Messages</h3>
                </div>
                <p className="text-blue-800">
                  Direct communication between individuals for private conversations.
                </p>
              </div>

              <div className="bg-yellow-50 p-6 rounded-lg border border-yellow-200">
                <div className="flex items-center mb-4">
                  <BellIcon className="h-8 w-8 text-yellow-500 mr-3" />
                  <h3 className="text-lg font-medium text-yellow-900">Notifications</h3>
                </div>
                <p className="text-yellow-800">
                  System-generated alerts about important events and updates.
                </p>
              </div>

              <div className="bg-green-50 p-6 rounded-lg border border-green-200">
                <div className="flex items-center mb-4">
                  <ChatBubbleLeftIcon className="h-8 w-8 text-green-500 mr-3" />
                  <h3 className="text-lg font-medium text-green-900">Issue Comments</h3>
                </div>
                <p className="text-green-800">
                  Public discussion attached to a specific issue or ticket.
                </p>
              </div>
            </div>

            <h3 className="text-lg font-medium mt-8 mb-4">Messages</h3>
            <div className="bg-gray-50 p-6 rounded-lg mb-6">
              <h4 className="font-medium mb-2">When to use Messages:</h4>
              <ul className="list-disc ml-6 space-y-2">
                <li>For private conversations between students and lecturers</li>
                <li>When information needs to be shared confidentially</li>
                <li>To discuss sensitive matters not related to a specific issue</li>
                <li>For direct follow-up on academic matters</li>
                <li>When you need a quick response from a specific person</li>
              </ul>
            </div>

            <h3 className="text-lg font-medium mt-8 mb-4">Notifications</h3>
            <div className="bg-gray-50 p-6 rounded-lg mb-6">
              <h4 className="font-medium mb-2">Understanding Notifications:</h4>
              <ul className="list-disc ml-6 space-y-2">
                <li>Automatically generated by the system</li>
                <li>Inform you about status changes to your issues</li>
                <li>Alert you when someone has commented on your issues</li>
                <li>Provide important university announcements</li>
                <li>Remind you of approaching deadlines or events</li>
              </ul>
            </div>

            <h3 className="text-lg font-medium mt-8 mb-4">Issue Comments</h3>
            <div className="bg-gray-50 p-6 rounded-lg mb-6">
              <h4 className="font-medium mb-2">When to comment on Issues:</h4>
              <ul className="list-disc ml-6 space-y-2">
                <li>To provide additional information about an issue</li>
                <li>To ask questions related to the specific issue</li>
                <li>To respond to staff questions about the issue</li>
                <li>To acknowledge or confirm that an issue has been resolved</li>
                <li>For public discussion that all stakeholders should see</li>
              </ul>
            </div>

            <h3 className="text-lg font-medium mt-8 mb-4">Staff Updates vs Comments</h3>
            <div className="bg-gray-50 p-6 rounded-lg mb-6">
              <p className="mb-4">
                For staff members (lecturers and administrators), there are two ways to add information to an issue:
              </p>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-yellow-50 p-4 rounded-lg border border-yellow-200">
                  <h4 className="font-medium mb-2 text-yellow-900">Updates</h4>
                  <p className="text-yellow-800 mb-2">Official status updates only visible to staff.</p>
                  <ul className="list-disc ml-6 space-y-1 text-yellow-800">
                    <li>For internal notes</li>
                    <li>Documenting actions taken</li>
                    <li>For official status changes</li>
                    <li>Not visible to students</li>
                  </ul>
                </div>
                
                <div className="bg-blue-50 p-4 rounded-lg border border-blue-200">
                  <h4 className="font-medium mb-2 text-blue-900">Comments</h4>
                  <p className="text-blue-800 mb-2">Public communication visible to all stakeholders.</p>
                  <ul className="list-disc ml-6 space-y-1 text-blue-800">
                    <li>For student-facing communication</li>
                    <li>Asking students for clarification</li>
                    <li>Explaining issue resolution</li>
                    <li>Visible to students and all staff</li>
                  </ul>
                </div>
              </div>
            </div>

            <h3 className="text-lg font-medium mt-8 mb-4">Best Practices</h3>
            <div className="bg-gray-50 p-6 rounded-lg">
              <ul className="list-disc ml-6 space-y-2">
                <li>Be clear and concise in all communications</li>
                <li>For sensitive information, use Messages rather than issue Comments</li>
                <li>Check your Notifications regularly for important updates</li>
                <li>When commenting on issues, mention relevant details like course codes or specific problems</li>
                <li>Staff should keep internal discussions in Updates, not in Comments</li>
                <li>Remember that all issue Comments become part of the permanent record</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CommunicationGuide; 