# Generated by Django 5.1.7 on 2025-04-01 10:10

from django.db import migrations
import uuid

def populate_student_numbers(apps, schema_editor):
    """
    Ensure both student_number and registration_number are populated.
    For existing records:
    - If student_number is empty but registration_number exists, copy registration_number to student_number
    - If registration_number is empty but student_number exists, copy student_number to registration_number
    - If both are empty, generate a unique value for both
    """
    Student = apps.get_model('users', 'Student')
    
    for student in Student.objects.all():
        # Case 1: Both empty - generate new values
        if not student.student_number and not student.registration_number:
            unique_id = f"STU{uuid.uuid4().hex[:8].upper()}"
            reg_id = f"REG{uuid.uuid4().hex[:8].upper()}"
            student.student_number = unique_id
            student.registration_number = reg_id
        
        # Case 2: student_number empty but registration_number exists
        elif not student.student_number and student.registration_number:
            # Generate a new student number based on registration_number
            student.student_number = f"S-{student.registration_number}"
        
        # Case 3: registration_number empty but student_number exists
        elif student.student_number and not student.registration_number:
            # Generate a new registration number based on student_number
            student.registration_number = f"R-{student.student_number}"
        
        # Case 4: Both exist - leave as is
        
        # Also ensure department is set from program if available
        if not student.department_id and student.program_id:
            program = student.program
            if hasattr(program, 'department'):
                student.department = program.department
        
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_student_department_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_student_numbers),
    ]
