# Generated by Django 5.1.7 on 2025-04-01 10:20

from django.db import migrations

def calculate_current_semester(apps, schema_editor):
    """
    Populate the current_semester field for all existing students
    based on their year_level and semester_in_year
    """
    Student = apps.get_model('users', 'Student')
    
    for student in Student.objects.all():
        # Calculate current_semester as ((year_level - 1) * 2) + semester_in_year
        year = student.year_level or 1
        semester = student.semester_in_year or 1
        current_semester = ((year - 1) * 2) + semester
        
        # Update the student record
        student.current_semester = current_semester
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_student_semester_student_current_semester_and_more'),
    ]

    operations = [
        migrations.RunPython(calculate_current_semester),
    ]
