# Generated by Django 5.1.7 on 2025-04-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.BigIntegerField(help_text='Unique student identifier number', unique=True),
        ),
    ]
