# Generated by Django 5.1.7 on 2025-04-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_student_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(help_text='Unique student identifier number', max_length=20, unique=True),
        ),
    ]
