# Generated by Django 5.1.7 on 2025-04-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
