# Generated by Django 5.1.7 on 2025-04-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_department_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
