# Generated by Django 5.1.7 on 2025-04-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_college_is_disabled'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('program_name', 'department')},
        ),
        migrations.AddField(
            model_name='program',
            name='code',
            field=models.CharField(blank=True, help_text='Program code/abbreviation (e.g., BSCS)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.CharField(default='3 years', help_text='Program duration (e.g., 3 years)', max_length=20),
        ),
        migrations.RemoveField(
            model_name='program',
            name='degree_level',
        ),
    ]
